Repository DeepDive-2nd-Project-Reviewers/customer, pull requests merged in 2025-01, with the labels that each got.

#3 [Feat] #2 도메인 초기 세팅
  .github/ISSUE_TEMPLATE/issue-template.md
  Dockerfile
  src/main/java/reviewers/customer/domain/Instructor/entity/Instructor.java
  src/main/java/reviewers/customer/domain/answer/entity/Answer.java
  src/main/java/reviewers/customer/domain/assignment/entity/Assignment.java
  src/main/java/reviewers/customer/domain/assignmentGrade/controller/AssignmentController.java
  src/main/java/reviewers/customer/domain/assignmentGrade/entity/AssignmentGrade.java
  src/main/java/reviewers/customer/domain/assignmentGrade/service/AssignmentService.java
  src/main/java/reviewers/customer/domain/content/entity/Content.java
  src/main/java/reviewers/customer/domain/course/entity/Course.java
  src/main/java/reviewers/customer/domain/lecture/entity/Lecture.java
  src/main/java/reviewers/customer/domain/question/entity/Question.java
  src/main/java/reviewers/customer/domain/quiz/entity/Quiz.java
  src/main/java/reviewers/customer/domain/quizGrade/controller/QuizController.java
  src/main/java/reviewers/customer/domain/quizGrade/entity/QuizGrade.java
  src/main/java/reviewers/customer/domain/quizGrade/service/QuizService.java
  src/main/java/reviewers/customer/domain/registration/entity/Registration.java
  src/main/java/reviewers/customer/domain/registration/enums/RegistrationStatus.java
  src/main/java/reviewers/customer/domain/student/entity/Student.java
  src/main/java/reviewers/customer/domain/teaching/entity/Teaching.java
  src/main/java/reviewers/customer/domain/user/entity/User.java
  src/main/java/reviewers/customer/domain/user/enums/Role.java
  src/main/java/reviewers/customer/global/common/BaseTimeEntity.java
  src/main/resources/application.yml
Labels: feat

#9 [Feat] 과제 점수 조회
  src/main/java/reviewers/customer/domain/assignment/entity/Assignment.java
  src/main/java/reviewers/customer/domain/assignment/entity/Submission.java
  src/main/java/reviewers/customer/domain/assignmentGrade/controller/AssignmentController.java
  src/main/java/reviewers/customer/domain/assignmentGrade/dto/AssignmentGradeListResponseDto.java
  src/main/java/reviewers/customer/domain/assignmentGrade/dto/AssignmentGradeRequestDto.java
  src/main/java/reviewers/customer/domain/assignmentGrade/dto/AssignmentGradeResponseDto.java
  src/main/java/reviewers/customer/domain/assignmentGrade/entity/AssignmentGrade.java
  src/main/java/reviewers/customer/domain/assignmentGrade/mapper/AssignmentGradeMapper.java
  src/main/java/reviewers/customer/domain/assignmentGrade/repository/AssignmentGradeRepository.java
  src/main/java/reviewers/customer/domain/assignmentGrade/service/AssignmentService.java
Labels: feat

#5 [Feat] 퀴즈 점수 조회 구현
  src/main/java/reviewers/customer/domain/quizGrade/controller/QuizController.java
  src/main/java/reviewers/customer/domain/quizGrade/dto/QuizGradeListResponseDto.java
  src/main/java/reviewers/customer/domain/quizGrade/dto/QuizGradeRequestDto.java
  src/main/java/reviewers/customer/domain/quizGrade/dto/QuizGradeResponseDto.java
  src/main/java/reviewers/customer/domain/quizGrade/mapper/QuizGradeMapper.java
  src/main/java/reviewers/customer/domain/quizGrade/repository/QuizGradeRepository.java
  src/main/java/reviewers/customer/domain/quizGrade/service/QuizService.java
Labels: feat

#8 [Feat] 과제 점수 통계 조회
  build.gradle
  src/main/java/reviewers/customer/domain/assignment/repository/AssignmentRepository.java
  src/main/java/reviewers/customer/domain/assignmentGrade/controller/AssignmentController.java
  src/main/java/reviewers/customer/domain/assignmentGrade/dto/AssignmentGradeOverallRequestDto.java
  src/main/java/reviewers/customer/domain/assignmentGrade/dto/AssignmentGradeOverallResponseDto.java
  src/main/java/reviewers/customer/domain/assignmentGrade/mapper/AssignmentGradeMapper.java
  src/main/java/reviewers/customer/domain/assignmentGrade/repository/AssignmentGradeRepository.java
  src/main/java/reviewers/customer/domain/assignmentGrade/service/AssignmentService.java
  src/main/java/reviewers/customer/domain/course/repository/CourseRepository.java
  src/main/java/reviewers/customer/domain/course/service/CourseService.java
  src/main/java/reviewers/customer/global/success/SuccessResponse.java
  src/main/java/reviewers/customer/global/success/SuccessResponseStatus.java
  src/main/resources/application.yml
Labels: feat

#10 [Fix] 병합 충돌 해결
  src/main/java/reviewers/customer/domain/assignmentGrade/controller/AssignmentController.java
  src/main/java/reviewers/customer/domain/assignmentGrade/mapper/AssignmentGradeMapper.java
  src/main/java/reviewers/customer/domain/assignmentGrade/repository/AssignmentGradeRepository.java
  src/main/java/reviewers/customer/domain/assignmentGrade/service/AssignmentService.java
Labels: fix

#12 [ Feat] http method 수정
  src/main/java/reviewers/customer/domain/assignmentGrade/controller/AssignmentController.java
  src/main/java/reviewers/customer/domain/assignmentGrade/dto/AssignmentGradeRequestDto.java
  src/main/java/reviewers/customer/domain/quizGrade/controller/QuizController.java
Labels: feat

#14 [ Feat] 깃액션 워크플로우 작성
  .github/workflows/docker-build-push.yml
  src/main/resources/application.yml
Labels: feat, fix

#16 [Fix] 도커파일 수정
  Dockerfile
Labels: fix

#17 [Fix] 도커파일 수정
  .github/workflows/docker-build-push.yml
Labels: fix

#18 fix: 워크플로우 수정
  .github/workflows/docker-build-push.yml
Labels: fix

#20 [Feat] swagger 추가
  build.gradle
  src/main/java/reviewers/customer/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: feat, fix

#21 [Fix] 설정 변경
  src/main/java/reviewers/customer/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: fix
